version: '3'
services:
  tos_api:
    tty: true
    build:
      context: .
    environment:
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: ${POSTGRES_HOST}
    volumes:
      - .:/api
    ports:
      - '3000:3000'

  tos_db:
    image: postgres:16.3
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ./.pgdata:/var/lib/postgresql/data

networks:
  default:
    external:
      name: tos_gateway