source "https://rubygems.org"

ruby "3.3.3"

gem "rails", "~> 7.1.3", ">= 7.1.3.4"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "bootsnap", require: false
gem "rack-cors", "~> 2.0.2"
gem "devise", "~> 4.9.4"
gem "devise-jwt", "~> 0.11.0"
gem "jsonapi-serializer", "~> 2.2.0"
gem "kaminari", "~> 1.2"
gem "has_scope", "~> 0.8.2"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem 'faker'
  gem "rspec-rails", "~> 6.1.3"
  gem "factory_bot_rails", "~> 6.4.3"
  gem "pry"
end

group :test do
  gem "database_cleaner-active_record", "~> 2.1.0"
  gem "shoulda-matchers", "~> 6.2.0"
end